name: test-configuration

on:
  push:
    paths:
      - 'config/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'config/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test-configuration:
    name: GraalVM ${{ matrix.version }} JDK${{ matrix.java-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [ latest, dev ]
        java-version: [ 11, 17 ]
        os: [ ubuntu-latest ] # TODO: Add support for macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: ${{ matrix.java-version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          python3 tests/run.py all
