name: "Validate library-and-framework-list.json"

on: [push, pull_request]

jobs:
  validate-library-and-framework-list-json:
    name: "📋 Checks if the json file is written according to the existing schema"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install check-jsonschema
      - run: check-jsonschema --schemafile library-and-framework-list-schema.json library-and-framework-list.json
      - run: ./gradlew spotlessJsonCheck
