name: "Validate library and framework list json"

on:
  push:
    paths:
      - 'library-and-framework-list.json'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: true

jobs:
  validate-library-and-framework-list-json:
    name: "📋 Checks if the json file is written according to the existing schema"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install jsonschema
      - run: check-jsonschema --schemafile ./library-and-framework-list-schema.json library-and-framework-list.json
      - name: "🕸️ Populate matrix"
        id: set-matrix
        run: |
          ./gradlew generateMatrixMatchingCoordinates -Pcoordinates=all
